using System;
using System.Collections.Generic;
using System.Text;

namespace CovidSharp.Constants
{
    public enum StateName
    {
        Alaska,
        Alabama,
        Arkansas,
        AmericanSamoa,
        Arizona,
        California,
        Colorado,
        Connecticut,
        WashingtonDC,
        Delaware,
        Florida,
        Georgia,
        Guam,
        Hawaii,
        Iowa,
        Idaho,
        Illinois,
        Indiana,
        Kansas,
        Kentucky,
        Louisiana,
        Massachusetts,
        Maryland,
        Maine,
        Michigan,
        Minnesota,
        Missouri, 
        MarianaIslands,
        Mississippi,
        Montana,
        NorthCarolina,
        NorthDakota,
        Nebraska,
        NewHampshire,
        NewJersey,
        NewMexico,
        Nevada,
        NewYork,
        Ohio,
        Oklahoma,
        Oregon,
        Pennsylvania,
        PuertoRico,
        RhodeIsland,
        SouthCarolina,
        SouthDakota,
        Tennessee,
        Texas,
        Utah,
        Virginia,
        VirginIslands,
        Vermont,
        Washington,
        Wisconsin,
        WestVirginia,
        Wyoming
    }
}
